import { ValidateResponsesButton } from "@carbonFootprint/view/screens/profile/components/forms/ValidateResponsesButton";
import { ListContentContainer } from "@carbonFootprint/view/screens/profile/components/lists/ListContentContainer";
import { ListItemQuestion } from "@carbonFootprint/view/screens/profile/components/lists/ListItemQuestion";
import { useEnergy } from "@carbonFootprint/view/screens/profile/housing/energy/useEnergy";

export const EnergySectionContent = () => {
  const { control, updateHousingProfile, energyQuestions } = useEnergy();

  return (
    <ListContentContainer>
      <ListItemQuestion
        question={energyQuestions.photovoltaicPanel}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.photovoltaicProduction}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="kWh"
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.photovoltaicPart}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="%"
        labelFlex={2}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.electricityConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="kWh"
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heatingEnergyType}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodType}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="kWh"
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasBottleConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2.5}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasPropaneConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="kg"
        labelFlex={1.25}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.fuelOilConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="litre(s)"
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodLogsConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="stère(s)"
        labelFlex={1}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heatNetworkConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="kWh"
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.bioGasContract}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.bioGasPart}
        control={control}
        handleUpdate={updateHousingProfile}
        affix="%"
        labelFlex={2}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        forceDisplay
        question={energyQuestions.airConditioningUsage}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.airConditioningNumber}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2.5}
        inputFlex={1}
      />
      <ValidateResponsesButton category="housing" subCategory="energy" />
    </ListContentContainer>
  );
};
