import { ValidateResponsesButton } from "@carbonFootprint/view/screens/profile/components/forms/ValidateResponsesButton";
import { ListContentContainer } from "@carbonFootprint/view/screens/profile/components/lists/ListContentContainer";
import { ListItemQuestion } from "@carbonFootprint/view/screens/profile/components/lists/ListItemQuestion";
import { useEnergy } from "@carbonFootprint/view/screens/profile/housing/energy/useEnergy";

export const EnergySectionContent = () => {
  const { control, updateHousingProfile, energyQuestions } = useEnergy();

  return (
    <ListContentContainer>
      <ListItemQuestion
        question={energyQuestions.heatingMode}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.preciseConsumptionInput}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.consumptionFeeling}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.dpe}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.waterHeatingMode}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heatingMain}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.waterHeatingMain}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.collectiveHeating}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.collectiveHeatingEcs}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heating}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodType}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      {/* <ListItemQuestion
        divider
        question={energyQuestions.woodLogs}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodOpenFire}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodStoveLogs}
        control={control}
        handleUpdate={updateHousingProfile}
      /> */}
      <ListItemQuestion
        divider
        question={energyQuestions.woodLogsConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodLogsPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
      />
      {/* <ListItemQuestion
        divider
        question={energyQuestions.woodPellets}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodStovePellets}
        control={control}
        handleUpdate={updateHousingProfile}
      /> */}
      <ListItemQuestion
        divider
        question={energyQuestions.woodPelletsConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.woodPelletsPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heatNetworkConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.heatNetworkPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasBottleConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2.5}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasPropaneConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.25}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.gasPropanePreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.25}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.bioGasContract}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.bioGasPart}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.fuelOilConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.fuelOilPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        forceDisplay
        question={energyQuestions.airConditioningUsage}
        control={control}
        handleUpdate={updateHousingProfile}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.airConditioningNumber}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2.5}
        inputFlex={1}
      />
      <ListItemQuestion
        question={energyQuestions.photovoltaicProduction}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.photovoltaicPart}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={2}
        inputFlex={1}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.electricityConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.electricityPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ListItemQuestion
        divider
        question={energyQuestions.electricityNetworkPreciseConsumption}
        control={control}
        handleUpdate={updateHousingProfile}
        labelFlex={1.1}
        inputFlex={1}
        step={100}
      />
      <ValidateResponsesButton category="housing" subCategory="energy" />
    </ListContentContainer>
  );
};
